# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b7cda777d6ff4c5568ae67f25e167471719a90806b99ff41945d48977979ed4547bd637bd6cad80db52b986a22d65bf26623b729eea0a05457cfffc61e42d43

test:
  secret_key_base: a8c0d5cd833a61127f2c7600ae78c34860886f929e82252d33ab5331711974814f9172a31572f931118bd9d30c7f635a134ea9327c82824f3d310ccaf5d4219a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
